[package]
name = "pc-example"
version = "0.1.0"
edition = "2024"

[dependencies]
protocrap = "0.1.20"
allocator-api2 = "0.2"

[build-dependencies]
protocrap = { version = "0.1.20", features = ["codegen"] }
